### PR TITLE
Region map interaction modes

### PR DESCRIPTION
**Pull request by tsherif**
Added new ways to interact with regions:
- `info`: just retrieve data associated with the selected region, no visual indicators
- `hide`: hide the selected region
- `isolate`: hide all regions other than the selected one.

The interaction style is set through the `mode` property of the region map, which can take the above values as well as `highlight` for the original highlighting behavior. I also renamed the regionMap node's `setHIghlightColor` to `setRegionColor`, since that's more appropriate now.

See the new `picking_region_*` examples for details.

### CODE REVIEW

**Comment by xeolabs** [comment]
Merged and [examples are now live](http://scenejs.org/examples/index.html#picking_regions_hide), thanks

**Comment by tsherif** [comment]
Thanks, but some of the source changes from [the second commit](https://github.com/xeolabs/scenejs/commit/4cc9ac85beef523dbc0f912c272a0b117d123c61) seem to be missing (in regionMap and programSourceFactory). Were there conflicts you had to resolve?

**Comment by xeolabs** [comment]
Ugh, I took care not to clobber anything, unbelievable. All I did was I
merge via github UI, pull, then push, to mirror to gh-pages. I'll try to do
the detective work later tonight.

On Sat, Dec 12, 2015 at 5:45 PM, Tarek Sherif <notifications@github.com>
wrote:

> Thanks, but some of the source changes from the second commit
> <https://github.com/xeolabs/scenejs/commit/4cc9ac85beef523dbc0f912c272a0b117d123c61>
> seem to be missing (in regionMap and programSourceFactory). Were there
> conflicts you had to resolve?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/pull/422#issuecomment-164167416>.
>



-- 
Lindsay Kay
http://xeolabs.com

**Comment by tsherif** [comment]
@xeolabs oh, I figured it out. The snapshot build is from the first commit. Would you mind doing a new snapshot build so the info example starts working (the regions aren't supposed to be highlighting in [](http://scenejs.org/examples/index.html#picking_regions_info))?

**Comment by xeolabs** [comment]
Sure, done. BTW I'm going to do another SceneJS release of the latest
changes in the new year - just need to prepare a few tutorials etc first,
eg. on the region mapping.

On Sat, Dec 12, 2015 at 6:09 PM, Tarek Sherif <notifications@github.com>
wrote:

> @xeolabs <https://github.com/xeolabs> oh, I figured it out. The snapshot
> build is from the first commit. Would you mind doing a new snapshot build
> so the info example starts working (the regions aren't supposed to be
> highlighting in
> <http://scenejs.org/examples/index.html#picking_regions_info>)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/pull/422#issuecomment-164169100>.
>



-- 
Lindsay Kay
http://xeolabs.com

**Comment by tsherif** [comment]
Cool! If you think I can help with anything, let me know.

**Comment by xeolabs** [comment]
OK no prob. Write ups are always good if you feel like adding any to the
wiki?  I'm also going to update the project pages to a new Bootstrap-based
website like xeoengine's
<https://github.com/xeolabs/xeoengine/tree/master/website> soon - time for
a bit of revamping I think.

And BTW longer term, one thing I I'd like to do is make a branch of SceneJS
that uses arrays for all vectors in the API (colors, positions etc), and
hopefully get Human to use arrays as well, but that would be a few months
off probably.

On Sat, Dec 12, 2015 at 6:15 PM, Tarek Sherif <notifications@github.com>
wrote:

> Cool! If you think I can help with anything, let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/pull/422#issuecomment-164169463>.
>



-- 
Lindsay Kay
http://xeolabs.com

**Pull request merged**
