### PR TITLE
Fixed shared memory bug in ray pick

### PR DESCRIPTION
**Pull request by tsherif**
This fixes a bug in the primitive picking code where it was reusing the arrays (`position`, `worldPos`, `barycentric`, `uv`, `normal`, `indices`) it was returning in the hit object. This meant that if the calling application was storing those values, it would find them changing with every new pick.

Another small change I made at the same time is to have the `position` and `wordPos` returned as vec3s rather than vec4s. Only the first 3 elements of the vec4 were ever used, which seemed confusing.

### CODE REVIEW

**Comment by xeolabs** [comment]
Cool in that case it makes sense for the event to have a copy of the
arrays. Note however that it's the general contract with events that the
properties on an event are only to be considered "valid" within the
lifetime of the handler callback, where the subscriber should not retain
references to event properties.

On Wed, Dec 16, 2015 at 6:06 PM, Tarek Sherif <notifications@github.com>
wrote:

> This fixes a bug in the primitive picking code where it was reusing the
> arrays (position, worldPos, barycentric, uv, normal, indices) it was
> returning in the hit object. This meant that if the calling application was
> storing those values, it would find them changing with every new pick.
>
> Another small change I made at the same time is to have the position and
> wordPos returned as vec3s rather than vec4s. Only the first 3 elements of
> the vec4 were ever used, which seemed confusing.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/xeolabs/scenejs/pull/424
> Commit Summary
>
>    - Fixed shared memory bug in ray pick
>
> File Changes
>
>    - *M* api/latest/scenejs.js
>    <https://github.com/xeolabs/scenejs/pull/424/files#diff-0> (34)
>    - *M* api/latest/scenejs.min.js
>    <https://github.com/xeolabs/scenejs/pull/424/files#diff-1> (8)
>    - *M* src/core/display/display.js
>    <https://github.com/xeolabs/scenejs/pull/424/files#diff-2> (32)
>
> Patch Links:
>
>    - https://github.com/xeolabs/scenejs/pull/424.patch
>    - https://github.com/xeolabs/scenejs/pull/424.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/pull/424>.
>



-- 
Lindsay Kay
http://xeolabs.com

**Comment by tsherif** [comment]
Oh, ok sure. If you feel that would be generally understood enough, then it might be best to leave it as is, as allocating new arrays will increase memory churn. Feel free to close this PR.

**Comment by tsherif** [comment]
Actually, @xeolabs I'm going to argue that those arrays shouldn't be re-used because the `hit` object [is also returned from the method](https://github.com/tsherif/scenejs/blob/raypick-fixes/src/core/display/display.js#L1329). While people might expect an event object to become invalid, I don't think they'd have the same expectations for the method's return value.

**Comment by xeolabs** [comment]
OK yes that's a point. I'll look at it tonight.

On Tue, Dec 22, 2015 at 3:35 PM, Tarek Sherif <notifications@github.com>
wrote:

> Actually, @xeolabs <https://github.com/xeolabs> I'm going to argue that
> those arrays shouldn't be re-used because the hit object is also returned
> from the method
> <https://github.com/tsherif/scenejs/blob/raypick-fixes/src/core/display/display.js#L1329>.
> While people might expect an event object to become invalid, I don't think
> they'd have the same expectations for the method's return value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/pull/424#issuecomment-166630326>.
>



-- 
Lindsay Kay
http://xeolabs.com

**Pull request merged**
